pipeline{

    agent any

    tools{
        maven 'maven'
    }

    stages{

        stage('BUILD'){
            steps{
                bat 'mvn -DskipTests package'
                echo '=====build completed======='
            }
        }

        stage('TEST'){
            steps{
                bat 'mvn test'
            }
            
            post{
                always{
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}